const tools = {
  'to-pdf': { label: 'In PDF umwandeln', title: 'Dateien in PDF umwandeln', description: 'Erstelle PDFs aus Dokumenten, Bildern und Web-Inhalten.', hint: 'Office-Dateien nutzen Microsoft Office; OpenOffice-Dateien bevorzugen LibreOffice. Beide bleiben lokal.', action: 'PDF erstellen', filter: [{ name: 'Unterstützte Dateien', extensions: ['txt', 'jpg', 'jpeg', 'png', 'html', 'htm', 'md', 'markdown', 'doc', 'docx', 'xls', 'xlsx', 'ppt', 'pptx', 'odt', 'ods', 'odp', 'rtf', 'pdf'] }] },
  'from-pdf': { label: 'PDF exportieren', title: 'PDF in ein anderes Format exportieren', description: 'Textinhalt lokal nach TXT, DOCX, HTML oder Markdown exportieren.', hint: 'DOCX wird als bearbeitbarer Text rekonstruiert; komplexe Seiten bleiben als Bild erhalten.', action: 'PDF exportieren', single: true, filter: [{ name: 'PDF-Dateien', extensions: ['pdf'] }] },
  merge: { label: 'PDFs zusammenfügen', title: 'PDFs zusammenfügen', description: 'Verbinde mehrere PDFs – deine Reihenfolge wird übernommen.', hint: 'Ordne die Dateien bei Bedarf per Drag & Drop oder mit den Pfeiltasten neu an.', action: 'PDFs zusammenfügen', minFiles: 2, filter: [{ name: 'PDF-Dateien', extensions: ['pdf'] }] },
  split: { label: 'PDF teilen', title: 'PDF an bestimmten Seiten teilen', description: 'Erstelle getrennte PDFs an einer oder mehreren gewünschten Stellen.', hint: 'Lege fest, nach welchen Seiten getrennt werden soll.', action: 'PDF teilen', single: true, filter: [{ name: 'PDF-Dateien', extensions: ['pdf'] }] },
  reorder: { label: 'Seiten neu anordnen', title: 'PDF-Seiten neu anordnen', description: 'Lege deine neue Seitenreihenfolge direkt mit den Seitennummern fest.', hint: 'Verschiebe Seiten per Drag & Drop oder über die Pfeiltasten.', action: 'PDF speichern', single: true, filter: [{ name: 'PDF-Dateien', extensions: ['pdf'] }] },
  compress: { label: 'PDF komprimieren', title: 'PDF komprimieren', description: 'Reduziere die Dateigröße mit einer passenden Qualitätsstufe.', hint: 'Die verlustlose Optimierung ist immer verfügbar. Stärkere Bildkomprimierung verwendet optional Ghostscript.', action: 'PDF komprimieren', single: true, filter: [{ name: 'PDF-Dateien', extensions: ['pdf'] }] }
};
const englishTools = {
  'to-pdf': { label: 'Convert to PDF', title: 'Convert files to PDF', description: 'Create PDFs from documents, images and web content.', hint: 'Office files use Microsoft Office; OpenOffice files prefer LibreOffice. Both stay local.', action: 'Create PDF' },
  'from-pdf': { label: 'Export PDF', title: 'Export a PDF to another format', description: 'Export text locally to TXT, DOCX, HTML or Markdown.', hint: 'DOCX is reconstructed as editable text; complex visual pages are retained as images.', action: 'Export PDF' },
  merge: { label: 'Merge PDFs', title: 'Merge PDFs', description: 'Combine multiple PDFs in your chosen order.', hint: 'Reorder files with drag and drop or the arrow buttons.', action: 'Merge PDFs' },
  split: { label: 'Split PDF', title: 'Split a PDF at selected pages', description: 'Create separate PDFs at one or more selected points.', hint: 'Choose the pages after which the document should split.', action: 'Split PDF' },
  reorder: { label: 'Reorder pages', title: 'Reorder PDF pages', description: 'Set the new page order directly using page numbers.', hint: 'Move pages with drag and drop or the arrow buttons.', action: 'Save PDF' },
  compress: { label: 'Compress PDF', title: 'Compress a PDF', description: 'Reduce file size with the appropriate quality level.', hint: 'Lossless optimization is always available. Stronger image compression optionally uses Ghostscript.', action: 'Compress PDF' }
};
const copy = {
  de: { language: 'Sprache', privacy: 'Lokal & privat', workflow: 'Auftragsfortschritt', files: 'Dateien', options: 'Optionen', destination: 'Zielordner', dropTitle: 'Dateien hier ablegen', dropCopy: 'oder über den Explorer auswählen', chooseFiles: 'Dateien auswählen', choosePdf: 'PDF auswählen', noFiles: 'Noch keine Dateien ausgewählt.', outputSettings: 'Ausgabe einstellen', prepared: 'Wird nach der Dateiauswahl passend vorbereitet.', noFolder: 'Noch kein Ordner ausgewählt', chooseFolder: 'Zielordner wählen', reset: 'Aktuelle Seite zurücksetzen', clear: 'Auswahl leeren', selectedFiles: 'Ausgewählte Dateien', mergeOrder: 'Reihenfolge der zusammengefügten PDFs', outputForMultiple: 'Ausgabe bei mehreren Dateien', combineSingle: 'Alle Dateien in eine PDF zusammenfassen', combineSeparate: 'Für jede Datei eine PDF erstellen', combineHelp: 'Standard: eine PDF in der Reihenfolge deiner Dateiauswahl.', outputFormat: 'Ausgabeformat', textFile: 'Textdatei (.txt)', wordFile: 'Word-Dokument (.docx)', webFile: 'Webseite (.html)', markdownFile: 'Markdown (.md)', splitAfter: 'Nach diesen Seiten teilen', splitHelp: 'Mehrere Trennstellen mit Komma trennen.', compression: 'Komprimierungsstufe', lossless: 'Verlustlos optimieren', balanced: 'Ausgewogen – kleinere Bilder', small: 'Kleinste Datei – für Web & E-Mail', compressionHelp: 'Stärkere Bildkomprimierung verwendet bei Verfügbarkeit Ghostscript.', choosePdfOrder: 'PDF auswählen – danach kannst du die Seiten direkt anordnen.', pageOrder: 'Die Reihenfolge von links nach rechts wird gespeichert.', page: 'Seite', up: 'Hoch', down: 'Runter', earlier: 'Vor', later: 'Zurück', destinationOpen: 'Zielordner öffnen', showInExplorer: 'Im Explorer anzeigen', processing: 'Wird verarbeitet …', done: 'Fertig', failed: 'Das hat nicht funktioniert', unknown: 'Unbekannter Fehler.', fileCreated: 'Datei wurde im Zielordner erstellt.', filesCreated: 'Dateien wurden im Zielordner erstellt.', oneFile: 'eine Datei', validOptions: 'gültige Optionen', aDestination: 'einen Zielordner', stillNeeded: 'Noch nötig: {items}', localOnly: 'Alles bereit. Die Verarbeitung erfolgt ausschließlich auf diesem Gerät.', processingLocal: 'Deine Dateien bleiben dabei ausschließlich auf diesem Gerät.', selectedFolder: 'Zielordner gewählt.', selectionCleared: 'Dateiauswahl geleert.', pageReset: 'Aktuelle Seite wurde zurückgesetzt.', toolReset: 'Dateiauswahl für das neue Werkzeug zurückgesetzt.', pagesFound: '{count} Seiten erkannt.', pagesReadFailed: 'Die Seitenzahl dieser PDF konnte nicht gelesen werden.', splitUnchecked: 'Die Seitenzahl wird nach der Dateiauswahl geprüft.', splitResult: 'Es entstehen {count} PDF-Dateien.', splitInvalid: 'Bitte Seiten zwischen 1 und {count} ohne Wiederholungen angeben.', removeFile: '{name} entfernen', newPageOrder: 'Neue Seitenreihenfolge', pagePosition: 'Seite {page}, Position {position}', preview: 'Vorschau: {name}', chooseOnePdf: 'oder eine PDF über den Explorer auswählen' },
  en: { language: 'Language', privacy: 'Local & private', workflow: 'Job progress', files: 'Files', options: 'Options', destination: 'Destination folder', dropTitle: 'Drop files here', dropCopy: 'or choose them in File Explorer', chooseFiles: 'Choose files', choosePdf: 'Choose PDF', noFiles: 'No files selected yet.', outputSettings: 'Output settings', prepared: 'Prepared after you select files.', noFolder: 'No folder selected yet', chooseFolder: 'Choose destination folder', reset: 'Reset current page', clear: 'Clear selection', selectedFiles: 'Selected files', mergeOrder: 'Order of merged PDFs', outputForMultiple: 'Output for multiple files', combineSingle: 'Combine all files into one PDF', combineSeparate: 'Create one PDF per file', combineHelp: 'Default: one PDF in the order you selected files.', outputFormat: 'Output format', textFile: 'Text file (.txt)', wordFile: 'Word document (.docx)', webFile: 'Web page (.html)', markdownFile: 'Markdown (.md)', splitAfter: 'Split after these pages', splitHelp: 'Separate multiple split points with commas.', compression: 'Compression level', lossless: 'Lossless optimization', balanced: 'Balanced – smaller images', small: 'Smallest file – web & email', compressionHelp: 'Stronger image compression uses Ghostscript when available.', choosePdfOrder: 'Choose a PDF – then you can reorder its pages directly.', pageOrder: 'The left-to-right order will be saved.', page: 'Page', up: 'Up', down: 'Down', earlier: 'Earlier', later: 'Later', destinationOpen: 'Open destination folder', showInExplorer: 'Show in File Explorer', processing: 'Processing …', done: 'Done', failed: 'That did not work', unknown: 'Unknown error.', fileCreated: 'file was created in the destination folder.', filesCreated: 'files were created in the destination folder.', oneFile: 'one file', validOptions: 'valid options', aDestination: 'a destination folder', stillNeeded: 'Still needed: {items}', localOnly: 'Everything is ready. Processing happens only on this device.', processingLocal: 'Your files remain exclusively on this device.', selectedFolder: 'Destination folder chosen.', selectionCleared: 'File selection cleared.', pageReset: 'Current page was reset.', toolReset: 'File selection was reset for the new tool.', pagesFound: '{count} pages detected.', pagesReadFailed: 'The page count of this PDF could not be read.', splitUnchecked: 'The page count is checked after you select a file.', splitResult: '{count} PDF files will be created.', splitInvalid: 'Enter pages between 1 and {count} without duplicates.', removeFile: 'Remove {name}', newPageOrder: 'New page order', pagePosition: 'Page {page}, position {position}', preview: 'Preview: {name}', chooseOnePdf: 'or choose a PDF in File Explorer' }
};
const state = { tool: 'to-pdf', files: [], outputDir: null, running: false, pageCount: null, pageOrder: [], thumbnails: {}, optionValid: true, notice: '', language: localStorage.getItem('pdf-werkstatt-language') || 'de' };
const $ = selector => document.querySelector(selector);
const fileName = file => file.split(/[\\/]/).pop();
const t = (key, values = {}) => (copy[state.language][key] || copy.de[key] || key).replace(/\{(\w+)\}/g, (_, name) => values[name] ?? '');
const toolConfig = (id = state.tool) => ({ ...tools[id], ...(state.language === 'en' ? englishTools[id] : {}) });
function moveItem(items, from, to) { if (to < 0 || to >= items.length || from === to) return; const [item] = items.splice(from, 1); items.splice(to, 0, item); }
function makeButton(label, className, handler, disabled = false) { const button = document.createElement('button'); button.className = className; button.textContent = label; button.disabled = disabled; button.addEventListener('click', handler); return button; }
function closeCustomSelects(except) { document.querySelectorAll('.custom-select.is-open').forEach(select => { if (select !== except) { select.classList.remove('is-open'); select.querySelector('.custom-select-trigger').setAttribute('aria-expanded', 'false'); } }); }
function makeCustomSelect(id, items, initialValue, onChange = () => {}) {
  const root = document.createElement('div'); root.id = id; root.className = 'custom-select'; root.dataset.value = initialValue; root.setAttribute('role', 'group');
  const trigger = document.createElement('button'); trigger.type = 'button'; trigger.className = 'custom-select-trigger'; trigger.setAttribute('aria-haspopup', 'listbox'); trigger.setAttribute('aria-expanded', 'false');
  const text = document.createElement('span'); text.className = 'custom-select-value'; const chevron = document.createElement('span'); chevron.className = 'custom-select-chevron'; chevron.innerHTML = '<svg viewBox="0 0 16 16" aria-hidden="true"><path d="m3 6 5 5 5-5"/></svg>'; trigger.append(text, chevron);
  const menu = document.createElement('div'); menu.className = 'custom-select-menu'; menu.setAttribute('role', 'listbox');
  const setValue = (value, notify = true) => { const choice = items.find(item => item[0] === value) || items[0]; root.dataset.value = choice[0]; text.textContent = choice[1]; menu.querySelectorAll('[role=option]').forEach(option => { const selected = option.dataset.value === choice[0]; option.classList.toggle('is-selected', selected); option.setAttribute('aria-selected', String(selected)); }); if (notify) onChange(choice[0]); };
  items.forEach(([value, label]) => { const option = document.createElement('button'); option.type = 'button'; option.className = 'custom-select-option'; option.dataset.value = value; option.setAttribute('role', 'option'); option.addEventListener('click', () => { setValue(value); root.classList.remove('is-open'); trigger.setAttribute('aria-expanded', 'false'); trigger.focus(); }); option.addEventListener('keydown', event => { const options = [...menu.querySelectorAll('.custom-select-option')]; const position = options.indexOf(option); if (event.key === 'ArrowDown') { event.preventDefault(); options[(position + 1) % options.length].focus(); } if (event.key === 'ArrowUp') { event.preventDefault(); options[(position - 1 + options.length) % options.length].focus(); } if (event.key === 'Escape') { root.classList.remove('is-open'); trigger.setAttribute('aria-expanded', 'false'); trigger.focus(); } }); option.textContent = label; menu.append(option); });
  const toggle = () => { const opening = !root.classList.contains('is-open'); closeCustomSelects(root); root.classList.toggle('is-open', opening); trigger.setAttribute('aria-expanded', String(opening)); };
  trigger.addEventListener('click', toggle); trigger.addEventListener('keydown', event => { if (event.key === 'ArrowDown' || event.key === 'ArrowUp') { event.preventDefault(); if (!root.classList.contains('is-open')) toggle(); const options = [...menu.querySelectorAll('.custom-select-option')]; options[event.key === 'ArrowDown' ? 0 : options.length - 1].focus(); } if (event.key === 'Escape') { root.classList.remove('is-open'); trigger.setAttribute('aria-expanded', 'false'); } });
  root.append(trigger, menu); setValue(initialValue, false); return root;
}
function renderStaticCopy() { document.documentElement.lang = state.language; document.querySelectorAll('[data-i18n]').forEach(element => { element.textContent = t(element.dataset.i18n); }); const reset = $('#reset-page'); reset.title = t('reset'); reset.setAttribute('aria-label', t('reset')); $('#workflow-status').setAttribute('aria-label', t('workflow')); $('#tool-nav').setAttribute('aria-label', state.language === 'en' ? 'PDF tools' : 'PDF-Werkzeuge'); }
function setTool(id) { if (id === state.tool) return; state.tool = id; state.files = []; state.pageCount = null; state.pageOrder = []; state.optionValid = true; state.notice = t('toolReset'); render(); }
function renderNavigation() { const nav = $('#tool-nav'); nav.replaceChildren(); Object.keys(tools).forEach(id => { const tool = toolConfig(id); nav.append(makeButton(tool.label, `nav-item ${id === state.tool ? 'selected' : ''}`, () => setTool(id))); }); }
function renderFiles() { const config = toolConfig(), list = $('#file-list'); $('#file-count').textContent = `${state.files.length} ${state.files.length === 1 ? (state.language === 'en' ? 'file' : 'Datei') : (state.language === 'en' ? 'files' : 'Dateien')}`; if (!state.files.length) { list.className = 'file-list empty'; list.innerHTML = `<p>${t('noFiles')}</p>`; return; } list.className = 'file-list'; list.replaceChildren(); const toolbar = document.createElement('div'); toolbar.className = 'file-list-toolbar'; const label = document.createElement('p'); label.textContent = state.tool === 'merge' ? t('mergeOrder') : t('selectedFiles'); toolbar.append(label, makeButton(t('clear'), 'text-button', () => { state.files = []; state.pageCount = null; state.pageOrder = []; state.notice = t('selectionCleared'); render(); })); list.append(toolbar); state.files.forEach((file, index) => { const row = document.createElement('div'); row.className = `file-row ${state.tool === 'merge' ? 'merge-preview-row' : ''}`; row.setAttribute('role', 'listitem'); if (['merge', 'to-pdf'].includes(state.tool)) { row.draggable = true; row.addEventListener('dragstart', event => { event.dataTransfer.setData('text/plain', index); row.classList.add('drag-source'); }); row.addEventListener('dragend', () => row.classList.remove('drag-source')); row.addEventListener('dragover', event => event.preventDefault()); row.addEventListener('drop', event => { event.preventDefault(); moveItem(state.files, Number(event.dataTransfer.getData('text/plain')), index); renderFiles(); }); } const preview = document.createElement('div'); preview.className = 'file-preview'; if (state.tool === 'merge' && state.thumbnails[file]?.[0]) { const image = new Image(); image.src = state.thumbnails[file][0]; image.alt = t('preview', { name: fileName(file) }); preview.append(image); } else preview.textContent = file.split('.').pop().toUpperCase(); const type = document.createElement('span'); type.className = 'file-type'; type.textContent = file.split('.').pop().toUpperCase(); const name = document.createElement('span'); name.className = 'file-name'; name.title = file; name.textContent = fileName(file); const controls = document.createElement('div'); controls.className = 'file-controls'; if (['merge', 'to-pdf'].includes(state.tool)) controls.append(makeButton(t('up'), 'move-button', () => { moveItem(state.files, index, index - 1); renderFiles(); }, index === 0), makeButton(t('down'), 'move-button', () => { moveItem(state.files, index, index + 1); renderFiles(); }, index === state.files.length - 1)); const remove = makeButton('×', 'remove-file', () => { state.files.splice(index, 1); refreshPdfInfo().then(render); }); remove.setAttribute('aria-label', t('removeFile', { name: fileName(file) })); controls.append(remove); row.append(preview, type, name, controls); list.append(row); }); if (config.single && state.files.length > 1) state.files = [state.files[0]]; }
function makeOption(labelText, field, helper = '') { const group = document.createElement('div'); group.className = 'field'; const text = document.createElement('span'); text.textContent = labelText; field.setAttribute('aria-label', labelText); group.append(text, field); if (helper) { const note = document.createElement('small'); note.textContent = helper; group.append(note); } return group; }
function splitValidity(value) { if (!state.pageCount) return { valid: true, message: t('splitUnchecked') }; const cuts = String(value).split(',').map(x => x.trim()).filter(Boolean).map(Number); const valid = cuts.length > 0 && cuts.every(x => Number.isInteger(x) && x > 0 && x < state.pageCount) && new Set(cuts).size === cuts.length; return { valid, message: valid ? t('splitResult', { count: cuts.length + 1 }) : t('splitInvalid', { count: state.pageCount - 1 }) }; }
function renderPageOrder(area) { if (!state.pageCount) { const note = document.createElement('p'); note.className = 'inline-note'; note.textContent = t('choosePdfOrder'); area.append(note); return; } const note = document.createElement('p'); note.className = 'inline-note'; note.textContent = `${state.pageCount} ${t('page').toLowerCase()}${state.pageCount === 1 ? '' : state.language === 'en' ? 's' : 'n'}. ${t('pageOrder')}`; const list = document.createElement('ol'); list.className = 'page-order-list'; list.setAttribute('aria-label', t('newPageOrder')); area.append(note, list); state.pageOrder.forEach((page, index) => { const item = document.createElement('li'); item.className = 'page-chip'; item.draggable = true; item.setAttribute('aria-label', t('pagePosition', { page, position: index + 1 })); item.addEventListener('dragstart', event => { event.dataTransfer.setData('text/plain', index); item.classList.add('drag-source'); }); item.addEventListener('dragend', () => item.classList.remove('drag-source')); item.addEventListener('dragover', event => event.preventDefault()); item.addEventListener('drop', event => { event.preventDefault(); moveItem(state.pageOrder, Number(event.dataTransfer.getData('text/plain')), index); renderOptions(); }); const preview = new Image(); preview.className = 'page-thumbnail'; preview.src = state.thumbnails[state.files[0]]?.[page - 1] || ''; preview.alt = `${t('page')} ${page}`; const value = document.createElement('span'); value.textContent = page; const controls = document.createElement('span'); controls.className = 'page-controls'; controls.append(makeButton(t('earlier'), 'move-button', () => { moveItem(state.pageOrder, index, index - 1); renderOptions(); }, index === 0), makeButton(t('later'), 'move-button', () => { moveItem(state.pageOrder, index, index + 1); renderOptions(); }, index === state.pageOrder.length - 1)); item.append(preview, value, controls); list.append(item); }); }
function renderOptions() {
  const area = $('#options'); area.replaceChildren(); state.optionValid = true;
  if (state.tool === 'to-pdf') area.append(makeOption(t('outputForMultiple'), makeCustomSelect('combine-output', [['single', t('combineSingle')], ['separate', t('combineSeparate')]], 'single'), t('combineHelp')));
  else if (state.tool === 'from-pdf') area.append(makeOption(t('outputFormat'), makeCustomSelect('format', [['txt', t('textFile')], ['docx', t('wordFile')], ['html', t('webFile')], ['md', t('markdownFile')]], 'txt')));
  else if (state.tool === 'split') { const input = document.createElement('input'); input.id = 'split-after'; input.value = '1'; input.placeholder = state.language === 'en' ? 'e.g. 3, 7' : 'z. B. 3, 7'; const feedback = document.createElement('p'); feedback.className = 'field-feedback'; const validate = () => { const result = splitValidity(input.value); state.optionValid = result.valid; feedback.textContent = result.message; feedback.classList.toggle('invalid', !result.valid); refreshRunButton(); }; input.addEventListener('input', validate); area.append(makeOption(t('splitAfter'), input, t('splitHelp')), feedback); validate(); }
  else if (state.tool === 'reorder') renderPageOrder(area);
  else if (state.tool === 'compress') area.append(makeOption(t('compression'), makeCustomSelect('compress-level', [['lossless', t('lossless')], ['balanced', t('balanced')], ['small', t('small')]], 'lossless'), t('compressionHelp')));
  else { const note = document.createElement('p'); note.className = 'inline-note'; note.textContent = toolConfig().hint; area.append(note); }
}
function updateWorkflow() { const config = toolConfig(); const hasFiles = state.files.length >= (config.minFiles || 1); const steps = { files: hasFiles, options: hasFiles && state.optionValid, destination: Boolean(state.outputDir) }; document.querySelectorAll('#workflow-status li').forEach(item => { const done = steps[item.dataset.step]; const active = !done && ((item.dataset.step === 'files' && !hasFiles) || (item.dataset.step === 'destination' && hasFiles)); item.classList.toggle('is-complete', done); item.classList.toggle('is-active', active); if (active) item.setAttribute('aria-current', 'step'); else item.removeAttribute('aria-current'); }); }
function refreshRunButton() { const config = toolConfig(), missing = []; if (state.files.length < (config.minFiles || 1)) missing.push(config.minFiles ? `${state.language === 'en' ? 'at least' : 'mindestens'} ${config.minFiles} ${state.language === 'en' ? 'files' : 'Dateien'}` : t('oneFile')); if (!state.optionValid) missing.push(t('validOptions')); if (!state.outputDir) missing.push(t('aDestination')); $('#run-button').disabled = Boolean(missing.length) || state.running; $('#readiness-hint').textContent = state.running ? t('processingLocal') : missing.length ? t('stillNeeded', { items: missing.join(' · ') }) : t('localOnly'); updateWorkflow(); }
function hideResult() { const panel = $('#result-panel'); panel.hidden = true; panel.replaceChildren(); }
function displayResult(kind, title, message, files = []) { const panel = $('#result-panel'); panel.hidden = false; panel.className = `result-panel ${kind}`; panel.replaceChildren(); const heading = document.createElement('h3'); heading.textContent = title; const text = document.createElement('p'); text.textContent = message; panel.append(heading, text); if (files.length > 1) panel.append(makeButton(t('destinationOpen'), 'result-file', () => window.pdfWerkstatt.openFolder(state.outputDir))); files.forEach(file => panel.append(makeButton(`${t('showInExplorer')}: ${fileName(file)}`, 'result-file', () => window.pdfWerkstatt.revealFile(file)))); }
async function refreshPdfInfo() { if (!['split', 'reorder'].includes(state.tool) || !state.files[0]) { state.pageCount = null; state.pageOrder = []; return; } try { const info = await window.pdfWerkstatt.getPdfInfo(state.files[0]); state.pageCount = info.pageCount; state.pageOrder = [...Array(info.pageCount).keys()].map(index => index + 1); const previews = await window.pdfWerkstatt.getPdfThumbnails(state.files[0], state.pageOrder); state.thumbnails[state.files[0]] = previews.map(item => item.dataUrl); state.notice = t('pagesFound', { count: info.pageCount }); } catch { state.pageCount = null; state.pageOrder = []; state.notice = t('pagesReadFailed'); } }
async function refreshMergeThumbnails() { if (state.tool !== 'merge') return; await Promise.all(state.files.map(async file => { try { const previews = await window.pdfWerkstatt.getPdfThumbnails(file, [1]); state.thumbnails[file] = previews.map(item => item.dataUrl); } catch { state.thumbnails[file] = []; } })); }
async function addFiles(files) { if (!files.length) return; const config = toolConfig(); state.files = config.single ? [files[0]] : [...state.files, ...files.filter(file => !state.files.includes(file))]; state.notice = ''; await refreshPdfInfo(); await refreshMergeThumbnails(); render(); }
async function chooseFiles() { await addFiles(await window.pdfWerkstatt.selectFiles(tools[state.tool].filter)); }
async function chooseFolder() { const folder = await window.pdfWerkstatt.selectOutputFolder(); if (!folder) return; state.outputDir = folder; state.notice = t('selectedFolder'); render(); hideResult(); }
function currentOptions() { if (state.tool === 'to-pdf') return { combine: $('#combine-output').dataset.value }; if (state.tool === 'from-pdf') return { format: $('#format').dataset.value }; if (state.tool === 'split') return { splitAfter: $('#split-after').value }; if (state.tool === 'reorder') return { order: state.pageOrder.join(',') }; if (state.tool === 'compress') return { level: $('#compress-level').dataset.value }; return {}; }
async function run() { state.running = true; refreshRunButton(); $('#run-button').textContent = t('processing'); hideResult(); try { const files = await window.pdfWerkstatt.runJob({ tool: state.tool, files: state.files, outputDir: state.outputDir, options: currentOptions() }); displayResult('success', t('done'), `${files.length} ${files.length === 1 ? t('fileCreated') : t('filesCreated')}`, files); } catch (error) { displayResult('error', t('failed'), error.message || t('unknown')); } finally { state.running = false; $('#run-button').textContent = toolConfig().action; refreshRunButton(); } }
function render() { const config = toolConfig(); renderStaticCopy(); renderNavigation(); $('#tool-title').textContent = config.title; $('#tool-description').textContent = config.description; $('#drop-copy').textContent = config.single ? t('chooseOnePdf') : t('dropCopy'); $('#choose-files').textContent = config.single ? t('choosePdf') : t('chooseFiles'); $('#run-hint').textContent = config.hint; $('#run-button').textContent = config.action; $('#option-summary').textContent = state.notice || t('prepared'); $('#destination-path').textContent = state.outputDir || t('noFolder'); renderFiles(); renderOptions(); refreshRunButton(); hideResult(); }
async function resetCurrentPage() { state.files = []; state.pageCount = null; state.pageOrder = []; state.optionValid = true; state.notice = t('pageReset'); state.outputDir = await window.pdfWerkstatt.getDefaultOutputFolder(); render(); }
$('#choose-files').addEventListener('click', chooseFiles); $('#choose-folder').addEventListener('click', chooseFolder); $('#run-button').addEventListener('click', run); $('#reset-page').addEventListener('click', resetCurrentPage);
const languageHost = $('#language-select'); languageHost.replaceWith(makeCustomSelect('language-select', [['de', 'Deutsch'], ['en', 'English']], state.language, value => { state.language = value; localStorage.setItem('pdf-werkstatt-language', state.language); render(); }));
document.addEventListener('click', event => { if (!event.target.closest('.custom-select')) closeCustomSelects(); });
const dropZone = $('#drop-zone'); ['dragenter', 'dragover'].forEach(type => dropZone.addEventListener(type, event => { event.preventDefault(); dropZone.classList.add('dragging'); })); ['dragleave', 'drop'].forEach(type => dropZone.addEventListener(type, event => { event.preventDefault(); dropZone.classList.remove('dragging'); })); dropZone.addEventListener('drop', async event => { const files = [...event.dataTransfer.files].map(file => file.path).filter(Boolean); await addFiles(files); });
render(); window.pdfWerkstatt.getDefaultOutputFolder().then(folder => { if (!state.outputDir && folder) { state.outputDir = folder; render(); } });
