const tools = {
  "to-pdf": {
    label: "In PDF umwandeln",
    title: "Dateien in PDF umwandeln",
    description: "Erstelle PDFs aus Dokumenten, Bildern und Web-Inhalten.",
    hint: "Office-Dateien nutzen Microsoft Office; OpenOffice-Dateien bevorzugen LibreOffice. Beide bleiben lokal.",
    action: "PDF erstellen",
    filter: [
      {
        name: "Unterstützte Dateien",
        extensions: [
          "txt",
          "jpg",
          "jpeg",
          "png",
          "html",
          "htm",
          "md",
          "markdown",
          "doc",
          "docx",
          "xls",
          "xlsx",
          "ppt",
          "pptx",
          "odt",
          "ods",
          "odp",
          "rtf",
          "pdf",
        ],
      },
    ],
  },
  "from-pdf": {
    label: "PDF exportieren",
    title: "PDF in ein anderes Format exportieren",
    description:
      "Textinhalt lokal nach TXT, DOCX, HTML oder Markdown exportieren.",
    hint: "DOCX wird als bearbeitbarer Text rekonstruiert; komplexe Seiten bleiben als Bild erhalten.",
    action: "PDF exportieren",
    single: true,
    filter: [{ name: "PDF-Dateien", extensions: ["pdf"] }],
  },
  merge: {
    label: "PDFs zusammenfügen",
    title: "PDFs zusammenfügen",
    description: "Verbinde mehrere PDFs – deine Reihenfolge wird übernommen.",
    hint: "Ordne die Dateien bei Bedarf per Drag & Drop oder mit den Pfeiltasten neu an.",
    action: "PDFs zusammenfügen",
    minFiles: 2,
    filter: [{ name: "PDF-Dateien", extensions: ["pdf"] }],
  },
  split: {
    label: "PDF teilen",
    title: "PDF an bestimmten Seiten teilen",
    description:
      "Erstelle getrennte PDFs an einer oder mehreren gewünschten Stellen.",
    hint: "Lege fest, nach welchen Seiten getrennt werden soll.",
    action: "PDF teilen",
    single: true,
    filter: [{ name: "PDF-Dateien", extensions: ["pdf"] }],
  },
  reorder: {
    label: "Seiten neu anordnen",
    title: "PDF-Seiten neu anordnen",
    description:
      "Lege deine neue Seitenreihenfolge direkt mit den Seitennummern fest.",
    hint: "Verschiebe Seiten per Drag & Drop oder über die Pfeiltasten.",
    action: "PDF speichern",
    single: true,
    filter: [{ name: "PDF-Dateien", extensions: ["pdf"] }],
  },
  compress: {
    label: "PDF komprimieren",
    title: "PDF komprimieren",
    description: "Reduziere die Dateigröße mit einer passenden Qualitätsstufe.",
    hint: "Die verlustlose Optimierung ist immer verfügbar. Stärkere Bildkomprimierung verwendet optional Ghostscript.",
    action: "PDF komprimieren",
    single: true,
    filter: [{ name: "PDF-Dateien", extensions: ["pdf"] }],
  },
};
const englishTools = {
  "to-pdf": {
    label: "Convert to PDF",
    title: "Convert files to PDF",
    description: "Create PDFs from documents, images and web content.",
    hint: "Office files use Microsoft Office; OpenOffice files prefer LibreOffice. Both stay local.",
    action: "Create PDF",
  },
  "from-pdf": {
    label: "Export PDF",
    title: "Export a PDF to another format",
    description: "Export text locally to TXT, DOCX, HTML or Markdown.",
    hint: "DOCX is reconstructed as editable text; complex visual pages are retained as images.",
    action: "Export PDF",
  },
  merge: {
    label: "Merge PDFs",
    title: "Merge PDFs",
    description: "Combine multiple PDFs in your chosen order.",
    hint: "Reorder files with drag and drop or the arrow buttons.",
    action: "Merge PDFs",
  },
  split: {
    label: "Split PDF",
    title: "Split a PDF at selected pages",
    description: "Create separate PDFs at one or more selected points.",
    hint: "Choose the pages after which the document should split.",
    action: "Split PDF",
  },
  reorder: {
    label: "Reorder pages",
    title: "Reorder PDF pages",
    description: "Set the new page order directly using page numbers.",
    hint: "Move pages with drag and drop or the arrow buttons.",
    action: "Save PDF",
  },
  compress: {
    label: "Compress PDF",
    title: "Compress a PDF",
    description: "Reduce file size with the appropriate quality level.",
    hint: "Lossless optimization is always available. Stronger image compression optionally uses Ghostscript.",
    action: "Compress PDF",
  },
};
const copy = {
  de: {
    language: "Sprache",
    conflictHandling: "Bei gleichem Dateinamen",
    renameConflicts: "Neue Datei nummerieren",
    overwriteConflicts: "Nachfragen und überschreiben",
    privacy: "Lokal & privat",
    tools: "Werkzeuge",
    ready: "Bereit",
    working: "Verarbeitung läuft",
    workflow: "Auftragsfortschritt",
    files: "Dateien",
    options: "Optionen",
    destination: "Zielordner",
    dropTitle: "Dateien hier ablegen",
    dropCopy: "oder über den Explorer auswählen",
    chooseFiles: "Dateien auswählen",
    choosePdf: "PDF auswählen",
    noFiles: "Noch keine Dateien ausgewählt.",
    outputSettings: "Ausgabe einstellen",
    prepared: "Wird nach der Dateiauswahl passend vorbereitet.",
    noFolder: "Noch kein Ordner ausgewählt",
    chooseFolder: "Zielordner wählen",
    reset: "Aktuelle Seite zurücksetzen",
    clear: "Auswahl leeren",
    selectedFiles: "Ausgewählte Dateien",
    mergeOrder: "Reihenfolge der zusammengefügten PDFs",
    outputForMultiple: "Ausgabe bei mehreren Dateien",
    combineSingle: "Alle Dateien in eine PDF zusammenfassen",
    combineSeparate: "Für jede Datei eine PDF erstellen",
    combineHelp: "Standard: eine PDF in der Reihenfolge deiner Dateiauswahl.",
    outputFormat: "Ausgabeformat",
    textFile: "Textdatei (.txt)",
    wordFile: "Word-Dokument (.docx)",
    webFile: "Webseite (.html)",
    markdownFile: "Markdown (.md)",
    splitAfter: "Nach diesen Seiten teilen",
    splitHelp: "Mehrere Trennstellen mit Komma trennen.",
    compression: "Komprimierungsstufe",
    lossless: "Verlustlos optimieren",
    balanced: "Ausgewogen – kleinere Bilder",
    small: "Kleinste Datei – für Web & E-Mail",
    compressionHelp:
      "Stärkere Bildkomprimierung verwendet bei Verfügbarkeit Ghostscript.",
    choosePdfOrder:
      "PDF auswählen – danach kannst du die Seiten direkt anordnen.",
    pageOrder: "Die Reihenfolge von links nach rechts wird gespeichert.",
    page: "Seite",
    up: "Hoch",
    down: "Runter",
    earlier: "Vor",
    later: "Zurück",
    destinationOpen: "Zielordner öffnen",
    showInExplorer: "Im Explorer anzeigen",
    processing: "Wird verarbeitet …",
    done: "Fertig",
    failed: "Das hat nicht funktioniert",
    unknown: "Unbekannter Fehler.",
    fileCreated: "Datei wurde im Zielordner erstellt.",
    filesCreated: "Dateien wurden im Zielordner erstellt.",
    oneFile: "eine Datei",
    validOptions: "gültige Optionen",
    aDestination: "einen Zielordner",
    stillNeeded: "Noch nötig: {items}",
    localOnly:
      "Alles bereit. Die Verarbeitung erfolgt ausschließlich auf diesem Gerät.",
    processingLocal:
      "Deine Dateien bleiben dabei ausschließlich auf diesem Gerät.",
    selectedFolder: "Zielordner gewählt.",
    selectionCleared: "Dateiauswahl geleert.",
    pageReset: "Aktuelle Seite wurde zurückgesetzt.",
    toolReset: "Dateiauswahl für das neue Werkzeug zurückgesetzt.",
    pagesFound: "{count} Seiten erkannt.",
    pagesReadFailed: "Die Seitenzahl dieser PDF konnte nicht gelesen werden.",
    splitUnchecked: "Die Seitenzahl wird nach der Dateiauswahl geprüft.",
    splitResult: "Es entstehen {count} PDF-Dateien.",
    splitInvalid:
      "Bitte Seiten zwischen 1 und {count} ohne Wiederholungen angeben.",
    removeFile: "{name} entfernen",
    newPageOrder: "Neue Seitenreihenfolge",
    pagePosition: "Seite {page}, Position {position}",
    preview: "Vorschau: {name}",
    chooseOnePdf: "oder eine PDF über den Explorer auswählen",
  },
  en: {
    language: "Language",
    conflictHandling: "When a file name already exists",
    renameConflicts: "Create a numbered copy",
    overwriteConflicts: "Ask before overwriting",
    privacy: "Local & private",
    tools: "Tools",
    ready: "Ready",
    working: "Processing",
    workflow: "Job progress",
    files: "Files",
    options: "Options",
    destination: "Destination folder",
    dropTitle: "Drop files here",
    dropCopy: "or choose them in File Explorer",
    chooseFiles: "Choose files",
    choosePdf: "Choose PDF",
    noFiles: "No files selected yet.",
    outputSettings: "Output settings",
    prepared: "Prepared after you select files.",
    noFolder: "No folder selected yet",
    chooseFolder: "Choose destination folder",
    reset: "Reset current page",
    clear: "Clear selection",
    selectedFiles: "Selected files",
    mergeOrder: "Order of merged PDFs",
    outputForMultiple: "Output for multiple files",
    combineSingle: "Combine all files into one PDF",
    combineSeparate: "Create one PDF per file",
    combineHelp: "Default: one PDF in the order you selected files.",
    outputFormat: "Output format",
    textFile: "Text file (.txt)",
    wordFile: "Word document (.docx)",
    webFile: "Web page (.html)",
    markdownFile: "Markdown (.md)",
    splitAfter: "Split after these pages",
    splitHelp: "Separate multiple split points with commas.",
    compression: "Compression level",
    lossless: "Lossless optimization",
    balanced: "Balanced – smaller images",
    small: "Smallest file – web & email",
    compressionHelp:
      "Stronger image compression uses Ghostscript when available.",
    choosePdfOrder: "Choose a PDF – then you can reorder its pages directly.",
    pageOrder: "The left-to-right order will be saved.",
    page: "Page",
    up: "Up",
    down: "Down",
    earlier: "Earlier",
    later: "Later",
    destinationOpen: "Open destination folder",
    showInExplorer: "Show in File Explorer",
    processing: "Processing …",
    done: "Done",
    failed: "That did not work",
    unknown: "Unknown error.",
    fileCreated: "file was created in the destination folder.",
    filesCreated: "files were created in the destination folder.",
    oneFile: "one file",
    validOptions: "valid options",
    aDestination: "a destination folder",
    stillNeeded: "Still needed: {items}",
    localOnly: "Everything is ready. Processing happens only on this device.",
    processingLocal: "Your files remain exclusively on this device.",
    selectedFolder: "Destination folder chosen.",
    selectionCleared: "File selection cleared.",
    pageReset: "Current page was reset.",
    toolReset: "File selection was reset for the new tool.",
    pagesFound: "{count} pages detected.",
    pagesReadFailed: "The page count of this PDF could not be read.",
    splitUnchecked: "The page count is checked after you select a file.",
    splitResult: "{count} PDF files will be created.",
    splitInvalid: "Enter pages between 1 and {count} without duplicates.",
    removeFile: "Remove {name}",
    newPageOrder: "New page order",
    pagePosition: "Page {page}, position {position}",
    preview: "Preview: {name}",
    chooseOnePdf: "or choose a PDF in File Explorer",
  },
};
copy.de.resetShort = "Zurücksetzen";
copy.en.resetShort = "Reset";
const state = {
  tool: "to-pdf",
  files: [],
  outputDir: null,
  running: false,
  pageCount: null,
  pageOrder: [],
  thumbnails: {},
  optionValid: true,
  notice: "",
  language: localStorage.getItem("pdf-werkstatt-language") || "de",
  conflictStrategy:
    localStorage.getItem("pagesmith-pdf-conflict-strategy") || "rename",
};
const $ = (selector) => document.querySelector(selector);
const fileName = (file) => file.split(/[\\/]/).pop();
const t = (key, values = {}) =>
  (copy[state.language][key] || copy.de[key] || key).replace(
    /\{(\w+)\}/g,
    (_, name) => values[name] ?? "",
  );
const toolConfig = (id = state.tool) => ({
  ...tools[id],
  ...(state.language === "en" ? englishTools[id] : {}),
});
